spring:
  datasource:
    username: root
    password: sonnettomysql
    url: jdbc:mysql://127.0.0.1:3306/orderdb
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:19092
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
stripe:
  api-key: sk_test_51Pj5rhP9Ug6EI0VqWjPjfT2spcyTNTF0F806ZMEumwrl5WdFRhwZk06MrL6TKGINfg9FZDhPXBLfJr4GCctKMFBl00pt9VPh1C
  client:
    success-url: http://127.0.0.1:3000/payment/success
    failure-url: http://127.0.0.1:3000/payment/failure
sonnetto:
  urls:
    user-service: http://127.0.0.1/8081/api/v1.0/users
    product-service: http://127.0.0.1/8083/api/v1.0/products