apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-service
  labels:
    app: ingredient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredient-service
  template:
    metadata:
      name: ingredient-service
      labels:
        app: ingredient-service
    spec:
      containers:
        - name: ingredient-service
          image: 961341518387.dkr.ecr.eu-north-1.amazonaws.com/w4t3rcs/sonnetto-ingredient-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloud-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ingredient-service
  labels:
    app: ingredient-service
spec:
  selector:
    app: ingredient-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer